feat: add findSubMatch behavior
updatecli/website pull request #250
Opened 2022-03-07 13:44 UTC by smerle33

As per : https://github.com/updatecli/updatecli/pull/551#issuecomment-1058903823
Adding information on findSubMatch.

2022-03-07 13:53 UTC, lemeurherve commented on content/docs/core/transformer.adoc
> +          pattern: '"(.*?):'
I would use an example with multiple possible sub matches here.

2022-03-07 13:53 UTC, dduportal commented on content/docs/core/transformer.adoc
> +          pattern: '"(.*?):'
Then 2 examples :)

2022-03-07 13:54 UTC, lemeurherve commented on content/docs/core/transformer.adoc
> +A findSubMatch rule capture the information by applying "pattern" as a regexp and using "captureIndex" value as the index for the capture to return (default 0).
```suggestion
A findSubMatch rule captures the desired information by applying "pattern" as a regexp and using "captureIndex" value as the index for the capture to return (default 0).
```

2022-03-07 14:00 UTC, smerle33 commented on content/docs/core/transformer.adoc
> +          pattern: '"(.*?):'
I updated this one, 2 exemples are not compliant with what's existing

2022-03-07 19:25 UTC, olblak commented
Thanks @smerle33 for the documentation \o/
I'll merge this pullrequest once we trigger the next updatecli release

2022-03-09 23:37 UTC, lemeurherve requested changes

2022-03-09 23:37 UTC, lemeurherve commented on content/docs/core/transformer.adoc
> +| captureIndex |-|-| "captureIndex" value defines the index of the capture to return (0 by default)
As discussed together, add explanation about "0" returning all submatches, and individual submatch indexes starting at 1

(In the example below, `captureIndex: 1` returns the `(.*?)` submatch)

2022-03-09 23:37 UTC, lemeurherve commented on content/docs/core/transformer.adoc
> +          pattern: '"(.*?):(.*)v'
```suggestion
          pattern: '"(.*?):(.*)'
```

2022-03-10 07:25 UTC, smerle33 commented on content/docs/core/transformer.adoc
> +| captureIndex |-|-| "captureIndex" value defines the index of the capture to return (0 by default)
awesome but I don't have the button to commit the suggestion ...

2022-03-10 13:10 UTC, lemeurherve commented on content/docs/core/transformer.adoc
> +| captureIndex |-|-| "captureIndex" value defines the index of the capture to return (0 by default)
It's a simple comment, not a suggestion, you'll need to go to the "files" tab and create a new suggestion from it, or copy/paste it in your local repo and commit then push it.

Note: this should also be added as comment in updatecli/updatecli corresponding code

2022-03-11 08:35 UTC, lemeurherve commented on content/docs/core/transformer.adoc
```suggestion
The `findSubmatch` below will return the submatch captured with `(.*?)`:
```

2022-03-11 08:36 UTC, lemeurherve commented on content/docs/core/transformer.adoc
> +| captureIndex |-|-| "captureIndex" value defines the index of the capture to return (0 by default)
```suggestion
| captureIndex |-|-| "captureIndex" value defines the index of the capture to return. Note that the default value `0` returns all submatches, and individual submatch indexes start at `1`.
```

2022-03-11 08:45 UTC, lemeurherve commented on content/docs/core/transformer.adoc
> +| captureIndex |-|-| "captureIndex" value defines the index of the capture to return (0 by default)
@smerle33 I've added the suggestions and the PR ;)

2022-03-11 09:14 UTC, lemeurherve approved these changes

2022-03-11 19:43 UTC, olblak approved these changes

2022-03-11 19:43 UTC, merged